staging:
  dialect: postgres
  datasource: host=127.0.0.1 port=5433 user=postgres password=secret dbname=postgres sslmode=disable
  dir: migrations
  table: migrations

development:
  dialect: sqlite3
  datasource: test.db
  dir: migrations/sqlite3

production:
  dialect: postgres
  datasource: host=${POSTGRESQL_HOST} port=${POSTGRESQL_PORT} user=${POSTGRESQL_USERNAME} password=${POSTGRESQL_PASSWORD} dbname=${POSTGRESQL_DATABASE} 
  dir: migrations
  table: migrations
