name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
        postgres: 
            image: postgres:12
            env:
              POSTGRES_USER: root
              POSTGRES_PASSWORD: secret
              POSTGRES_DB: simple_bank
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install golang-migrate
      run: |
        curl -L -o migrate.tar.gz https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz
        tar -xvzf migrate.tar.gz
        sudo mv migrate /usr/bin/
        migrate --version

    - name: Install sql-migrate
      run: |
        go install github.com/rubenv/sql-migrate/...@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Run migration
      run: make migrateup

    - name: Test
      run: make test